[workspace]
members = [
    "uchat-apksigner",
    "uchat-builder",
    "uchat-hybrid-signer",
    "uchat-native",
    "uchat-zipalign",
    "uchat-v1sig",
    "uchat-v1sig-assembler",
    "uchat-v2sig",
    "uchat-signer-meta"
]
